<pre>
<?php 
$url = 'http://www.ynet.co.il/Integration/StoryRss1854.xml';
$rss = simplexml_load_file($url);

$titles = array();
foreach($rss->channel->item as $item) {
	$title = (string) $item->title;
	$title = trim($title);
	if (! empty($title)) {
		$titles[] = $title;
	}
}
?>
</pre>

<script type="text/javascript">
var ynet = <?php echo json_encode($titles); ?>;
var logo = jQuery('.zdb-toolbar-entry[data-extension="ynet"] .zdb-toolbar-icon')[0];

var wrapper = document.createElement("div");
wrapper.appendChild(logo);
logo = wrapper.innerHTML;

jQuery('.zdb-toolbar-entry[data-extension="ynet"]').replaceWith('<div class="zdb-toolbar-entry" data-extension="ynet"><div class="zdb-toolbar-preview" title="ynet">' + logo + '<span class="zdb-toolbar-info">Loading...</span></div><div class="zdb-toolbar-detail zdb-toolbar-detail-redundant"></div></div>');

jQuery('.zdb-toolbar-entry[data-extension="ynet"] .zdb-toolbar-info').html(ynet[0]);

setInterval(function() {
	var rand = Math.floor(Math.random() * ynet.length);
	jQuery('.zdb-toolbar-entry[data-extension="ynet"] .zdb-toolbar-info').html(ynet[rand].substr(0, 70));
}, 4000);
</script>